python train.py --batch 128\
    --weights yolov5s.pt\
    --data data.yaml\
    --epochs 300\
    --img 320 \
    --device 0 \
    --cache \
    --freeze 10 \
    --adam \
    --hyp data/hyps/hyp.finetune.yaml \
    --patience 20
